# This is a template for setting up a blog page using mkdocs-bloggin-plugin
# (https://github.com/liang2kl/mkdocs-blogging-plugin). Please follow the
# guide (https://liang2kl.github.io/mkdocs-blogging-plugin) for further
# customization. You can also follow an example project
# (https://liang2kl.github.io/mkdocs-blogging-plugin-example) to customize
# the appearance using templates.

# [NOTE] change this to your site name
site_name: Blog Template
# [NOTE] change this to your site url
site_url: https://liang2kl.github.io/mkdocs-blogging-plugin-bootstrap/
# [NOTE] change these three repo settings, delete them if not desired
repo_url: https://github.com/liang2kl/mkdocs-blogging-plugin-bootstrap/
repo_name: liang2kl/mkdocs-blogging-plugin-example
edit_uri: ""

# [NOTE] edit mkdocs configs as normal
theme:
  name: 'material'

plugins:
  - blogging:
      # ============================================================================
      # [SECTION] global category
      # [NOTE]    referenced by {{ blog_content }}
      # [REF]     https://liang2kl.github.io/mkdocs-blogging-plugin/#category-specific-settings

      dirs:
        - blog

      # ============================================================================
      # [SECTION] additional categories (optional)
      # [NOTE]    referenced by {{ blog_content <category_name> }}
      # [NOTE]    if you are not using them, please delete the `review` directory
      # [REF]     https://liang2kl.github.io/mkdocs-blogging-plugin/#categories
      #           https://liang2kl.github.io/mkdocs-blogging-plugin/#category-specific-settings

      categories:
        - name: reviews
          dirs:
            - reviews
      
      # ============================================================================
      # [SECTION] global configurations (optional)
      # [NOTE]    configs that apply to all categories
      # [REF]     https://liang2kl.github.io/mkdocs-blogging-plugin/#global-settings

      features:
        tags:
          index_page: tags.md
          insert: top
